login and scope pages
ChampionFX/binary-style pull request #18
Opened 2017-01-09 20:47 UTC by sashcy

2017-01-10 01:04 UTC, ashkanx requested changes
This should be in SASS format.

2017-01-10 01:28 UTC, sashcy commented
Fixed

2017-01-10 02:03 UTC, negarn commented on _sass/common.scss
> +.fx-acc {
@sashcy seems this element doesn't exist in oauth page, are you planning to create a separate PR for that to add this element? or is it better to use the existing elements?

2017-01-10 02:06 UTC, sashcy commented on _sass/common.scss
> +.fx-acc {
No, I sent new pages for oath (login and scope) where fx-login is renamed to fx-acc so it can be reused.

2017-01-11 01:54 UTC, ashkanx commented on _sass/common.scss
> +.fx-acc {
Sash, can you send the HTML of both pages to me? I can't find them in my email.

2017-01-11 02:09 UTC, ashkanx approved these changes

2017-01-11 02:09 UTC, merged