design change of champion style
ChampionFX/binary-style pull request #26
Opened 2017-03-05 14:10 UTC by nazaninreihani

2017-03-09 08:50 UTC, mohammad-deriv requested changes

2017-03-09 08:50 UTC, binary-hamedanchi commented on _sass/mixin.scss
> +        li.active, li.ui-tabs-active {
Would you please check all the indentations in your changes and make corrections where needed?
Thanks.

2017-03-09 08:55 UTC, nazaninreihani commented on _sass/mixin.scss
> +        li.active, li.ui-tabs-active {
sure

2017-03-10 03:00 UTC, mohammad-deriv approved these changes

2017-03-10 03:21 UTC, merged